//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.datacore.com.example", ConfigurationName="ServiceReference1.IEcho")]
    public interface IEcho {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.datacore.com.example/IEcho/Echo", ReplyAction="http://www.datacore.com.example/IEcho/EchoResponse")]
        string Echo(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.datacore.com.example/IEcho/Echo", ReplyAction="http://www.datacore.com.example/IEcho/EchoResponse")]
        System.Threading.Tasks.Task<string> EchoAsync(string s);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEchoChannel : WcfClient.ServiceReference1.IEcho, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EchoClient : System.ServiceModel.ClientBase<WcfClient.ServiceReference1.IEcho>, WcfClient.ServiceReference1.IEcho {
        
        public EchoClient() {
        }
        
        public EchoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EchoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EchoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EchoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Echo(string s) {
            return base.Channel.Echo(s);
        }
        
        public System.Threading.Tasks.Task<string> EchoAsync(string s) {
            return base.Channel.EchoAsync(s);
        }
    }
}
